[package]
name = "bhyve-api"
version = "0.0.1"
authors = ["Allison Randal <allison@oxide.computer>"]
edition = "2018"

[dependencies]
libc = "*"
num_enum = "0.5"
vmm-sys-util = { git = "https://github.com/rust-vmm/vmm-sys-util" }
